## Import Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.svm import SVC, SVR
from sklearn.preprocessing import MinMaxScaler

from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, StratifiedKFold
from sklearn.metrics import confusion_matrix, classification_report

import matplotlib.pyplot as plt
import seaborn as sns

### Gathering Data 

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")

In [3]:
df.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [4]:
df["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [5]:
df["Gender"] = df["Gender"].replace({"Male":1, "Female":0})

C:\Users\khedk\AppData\Local\Temp\ipykernel_25460\2139476155.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Gender"] = df["Gender"].replace({"Male":1, "Female":0})


In [6]:
df.drop("User ID",axis = 1, inplace= True)

In [7]:
df

Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

In [8]:
x = df.drop("Purchased",axis = 1)
y = df["Purchased"]

In [9]:
x

Gender  Age  EstimatedSalary
0         1   19            19000
1         1   35            20000
2         0   26            43000
3         0   27            57000
4         1   19            76000
..      ...  ...              ...
395       0   46            41000
396       1   51            23000
397       0   50            20000
398       1   36            33000
399       0   49            36000

[400 rows x 3 columns]

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [11]:
scaler = MinMaxScaler()

In [12]:
# Tranform the features into fixed range of elemets 

In [13]:
scaler.fit(x_train)

MinMaxScaler()

In [14]:
x_train = scaler.transform(x_train)

In [15]:
x_train = pd.DataFrame(x_train, columns= x.columns)

In [16]:
x_train

Gender       Age  EstimatedSalary
0       1.0  0.523810         0.340741
1       1.0  0.238095         0.800000
2       1.0  0.142857         0.059259
3       1.0  0.190476         0.488889
4       0.0  0.976190         0.103704
..      ...       ...              ...
295     1.0  0.095238         0.022222
296     1.0  0.404762         0.296296
297     0.0  0.952381         0.637037
298     1.0  0.214286         0.540741
299     0.0  0.690476         0.725926

[300 rows x 3 columns]

In [17]:
# While scaling is a type of transformation, the term "transform" encompasses a wider 
# range of operations that can fundamentally change the distribution or type of a feature, 
# not just its scale. Scalers specifically focus on adjusting the numerical range, whereas 
# transformations can alter the shape of the distribution, convert data types, or create 
# new features from existing ones.

### Model Training

In [18]:
svc_model = SVC()
svc_model.fit(x_train,y_train)

SVC()

In [19]:
parameters = svc_model.get_params()
parameters

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

### Model Evaluation

####  On test data 

In [20]:
y_pred = svc_model.predict(x_test)

In [21]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
conf_matrix = confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(conf_matrix)
print()
print("Classification Report")
print(classification_report(y_test,y_pred))

C:\Users\khedk\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix
[[ 0 67]
 [ 0 33]]

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        67
           1       0.33      1.00      0.50        33

    accuracy                           0.33       100
   macro avg       0.17      0.50      0.25       100
weighted avg       0.11      0.33      0.16       100



C:\Users\khedk\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\khedk\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


####  On Train  Data

In [23]:
y_pred_train = svc_model.predict(x_train)

In [24]:
y_pred_train

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1])

In [25]:
conf_matrix = confusion_matrix(y_train,y_pred_train)
print("Confusion Matrix:")
print(conf_matrix)
print()
print("Classification Report")
print(classification_report(y_train,y_pred_train))

Confusion Matrix:
[[174  16]
 [ 13  97]]

Classification Report
              precision    recall  f1-score   support

           0       0.93      0.92      0.92       190
           1       0.86      0.88      0.87       110

    accuracy                           0.90       300
   macro avg       0.89      0.90      0.90       300
weighted avg       0.90      0.90      0.90       300



### Hyperparameter Tuning

In [33]:
svc_model = SVC()

param_grid = {"C":np.arange(1,50),
    "kernel":["linear","poly","rbf","sigmoid"]
}

kfold = StratifiedKFold(n_splits=3,shuffle=True,random_state=10)

gsvc_svc_model = GridSearchCV(svc_model,param_grid,cv = kfold)

gsvc_svc_model.fit(x_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=10, shuffle=True),
             estimator=SVC(),
             param_grid={'C': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [35]:
gsvc_svc_model.best_estimator_

SVC(C=np.int64(28))

In [36]:
gsvc_svc_model.best_estimator_.get_params()

{'C': np.int64(28),
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

### Model Evaluation

In [37]:
y_pred = gsvc_svc_model.best_estimator_.predict(scaler.transform(x_test))

conf_matrix = confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(conf_matrix)
print()
print("Classification Report")
print(classification_report(y_test,y_pred))

Confusion Matrix:
[[61  6]
 [ 2 31]]

Classification Report
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        67
           1       0.84      0.94      0.89        33

    accuracy                           0.92       100
   macro avg       0.90      0.92      0.91       100
weighted avg       0.93      0.92      0.92       100



C:\Users\khedk\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


#### OnTrain Data

In [38]:
y_pred_train = gsvc_svc_model.best_estimator_.predict(x_train)

conf_matrix = confusion_matrix(y_train,y_pred_train)
print("Confusion Matrix:")
print(conf_matrix)
print()
print("Classification Report")
print(classification_report(y_train,y_pred_train))

Confusion Matrix:
[[174  16]
 [  9 101]]

Classification Report
              precision    recall  f1-score   support

           0       0.95      0.92      0.93       190
           1       0.86      0.92      0.89       110

    accuracy                           0.92       300
   macro avg       0.91      0.92      0.91       300
weighted avg       0.92      0.92      0.92       300

